### ISSUE TITLE
Segmentation fault when add the robot model into Rviz (ver 1.11.3)

### ISSUE THREAD

**Issue by robotpilot** [ros/robot_model#80] opened 2014-07-04 06:13 UTC
Today, I just runt the "rosrun rviz rviz" command, and then add the robot model into RViz.
(used the robot_model ver 1.11.3 and ROS Indigo)

But, RViz is shutdown. 
I saw the "Segmentation fault" error when add the robot model component into Rviz.

**Comment by wjwwood** [comment] 2014-07-07 00:43
I really need a backtrace from gdb/lldb or reproducible sequence of events to do anything with this. If you can't reproduce to provide those things I would ask you to close the issue. That way people can still find it in search, but it doesn't imply action needs to be taken.

**Comment by robotpilot** [comment] 2014-07-07 00:46
Ok. William Woodall. I close this issue. Thanks...

**Closed as completed** 2014-07-07 00:46 UTC
