### ISSUE TITLE
kdl_parser as ros_build dependency causes error in service generation (hydro)

### ISSUE THREAD

**Issue by tstoyanov** [ros/robot_model#47] opened 2013-12-05 10:52 UTC
I encountered a very strange issue with kdl_parser when updating to hydro. I have a dry package that depends on kdl_parser and also defines some services. Running rosmake on the package produces an error in generating the services. If the dependency to kdl_parser is removed, the issue is resolved. 

To reproduce the bug:
roscreate-pkg test kdl_parser sensor_msgs
cd test
mkdir srv
echo -e 'sensor_msgs/PointCloud2 in \n---\nsensor_msgs/PointCloud2 out' > srv/Test.srv
echo "rosbuild_gensrv()" >> CMakeLists.txt
rosmake

Output:
  Traceback (most recent call last):
    File "/opt/ros/hydro/share/roslisp/rosbuild/scripts/genmsg_lisp.py", line 873, in <module>
      generate_srv(sys.argv[1])
    File "/opt/ros/hydro/share/roslisp/rosbuild/scripts/genmsg_lisp.py", line 822, in generate_srv
      write_srv_component(s, spec.request, spec)
    File "/opt/ros/hydro/share/roslisp/rosbuild/scripts/genmsg_lisp.py", line 697, in write_srv_component
      write_md5sum(s, spec, parent)
    File "/opt/ros/hydro/share/roslisp/rosbuild/scripts/genmsg_lisp.py", line 596, in write_md5sum
      compute_files=False)
    File "/opt/ros/hydro/lib/python2.7/dist-packages/roslib/gentools.py", line 325, in get_dependencies
      raise MsgSpecException("Cannot load type %s.  Perhaps the package is missing a dependency."%(str(e)))
  roslib.msgs.MsgSpecException: Cannot load type 'sensor_msgs/PointCloud2'.  Perhaps the package is missing a dependency.

**Comment by isucan** [comment] 2013-12-05 15:51
Hey Todor,
This sounds pretty odd. Simple thing - did you double check that the manifest.xml has a dep on sensor_msgs as well when you use kdl_parser? Is the behaviour the same if you replace kdl_parser by roscpp for example?

@dirk-thomas

**Comment by tstoyanov** [comment] 2013-12-05 15:57
Hi Ioan,
yes, there is a dep on sensor_msgs. It builds fine when I change the dep from kdl_parser to roscpp. Odd for sure.

**Comment by isucan** [comment] 2013-12-05 16:01
What is the version of kdl_parser? Does the same thing happen is you use orocos_kdl as a dep?

**Comment by tstoyanov** [comment] 2013-12-05 16:05
kdl_parser version: 1.10.17
orocos_kdl works fine. 
Did you manage to reproduce the bug on your side?

**Comment by isucan** [comment] 2013-12-06 07:10
I cannot reproduce this. I tried with the version of kdl_parser from debs and the one from src as well.

**Comment by tstoyanov** [comment] 2013-12-10 15:44
Hi,
so I managed to reproduce it on two other machines both running hydro over ubuntu 12.04, latest package releases from aptitude. I didn't manage to reproduce under groovy on 12.04 or 11.10 (the only options I had handy as virtual machines around). 
Might be an issue with the particular binaries released for 12.04?
I will try to test on other architectures as well and let you know if the problem persists.

**Comment by jackieokay** [comment] 2016-01-28 22:24
Going to look into this. If it I can't reproduce it Indigo then I'm going to label this as wontfix.

**Comment by jackieokay** [comment] 2016-01-29 01:36
Confirmed to work on Indigo with 14.04.

**Closed as completed** 2016-01-29 01:40 UTC
Labels: wontfix
